// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import '../config/env_config.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// API keys are loaded from environment variables at build time.
/// Use: flutter run --dart-define=FIREBASE_WEB_API_KEY=xxx --dart-define=FIREBASE_ANDROID_API_KEY=xxx
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: EnvConfig.firebaseWebApiKey,
    appId: '1:737168565040:web:b8c3bc6dd6eb6cb3f1def5',
    messagingSenderId: '737168565040',
    projectId: 'my-gym-app-59ffb',
    authDomain: 'my-gym-app-59ffb.firebaseapp.com',
    storageBucket: 'my-gym-app-59ffb.firebasestorage.app',
    measurementId: 'G-DCEFWRN8GE',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: EnvConfig.firebaseAndroidApiKey,
    appId: '1:737168565040:android:6389b3ded5828becf1def5',
    messagingSenderId: '737168565040',
    projectId: 'my-gym-app-59ffb',
    storageBucket: 'my-gym-app-59ffb.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: EnvConfig.firebaseIosApiKey,
    appId: '1:737168565040:ios:b1b6086127661833f1def5',
    messagingSenderId: '737168565040',
    projectId: 'my-gym-app-59ffb',
    storageBucket: 'my-gym-app-59ffb.firebasestorage.app',
    iosBundleId: 'com.example.gymApp',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: EnvConfig.firebaseIosApiKey,
    appId: '1:737168565040:ios:b1b6086127661833f1def5',
    messagingSenderId: '737168565040',
    projectId: 'my-gym-app-59ffb',
    storageBucket: 'my-gym-app-59ffb.firebasestorage.app',
    iosBundleId: 'com.example.gymApp',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: EnvConfig.firebaseWebApiKey,
    appId: '1:737168565040:web:756853bc0da73d48f1def5',
    messagingSenderId: '737168565040',
    projectId: 'my-gym-app-59ffb',
    authDomain: 'my-gym-app-59ffb.firebaseapp.com',
    storageBucket: 'my-gym-app-59ffb.firebasestorage.app',
    measurementId: 'G-0Z5H5WL3CL',
  );
}
